### ISSUE TITLE
version of linux

### ISSUE THREAD

**Issue by YoinkedYoink** [R00tS3c/DDOS-RootSec#11]
what version of cent os would most, if not all, of these scripts work in?

**Comment by AlenFarky** [comment]
CentOS 7 definitely, just make sure that you learn GNU compiler better known as (GCC).
For all of the scripts that are made with extension .c (which means that its code have been writen in C) just use command: gcc -o name of file you want script.c. Btw very big procent of scripts are need -pthread create after the gcc command so it would be like this. In example script name is test.c so: gcc test test.c -phtread create. And you run it like normal bash script you can do ./test or bash test its your own opinion. Hope that I helped you, bye.

**Comment by R00tS3c** [comment]
Any if you know how to compile them
