### ISSUE TITLE
ImportError: No module named paramiko

### ISSUE THREAD

**Issue by shon4840** [R00tS3c/DDOS-RootSec#26]
Traceback (most recent call last):
  File "Attack.py", line 12, in <module>
    import threading, paramiko, random, socket, time, os, sys
ImportError: No module named paramiko

google did not help immediately i say

i don’t know what it is, i already installed everything and ran it through python 2 and 3 but it doesn't work for me so half of the repository does not work if it’s a script for scanning bots i tried all the python scripts there but none of them work please help me this is really very necessary

kali linux 2022.4 Everything
![Screenshot_20230130_215852](https://user-images.githubusercontent.com/69123413/215582730-7e5f45f6-e91c-4131-90bc-2c3ecfb3be6a.png)

**Comment by R00tS3c** [comment]
LEARN TO USE PYTHON OR ASK HERE https://t.me/realsecgroup IM NOT ANSWERING ON STUPED QUESTIONS.
