### ISSUE TITLE
Zipping Malware

### ISSUE THREAD

**Issue by TechnicSmile** [R00tS3c/DDOS-RootSec#3]
Overall I love this GitHub, it contains a lot of great samples. The only issue with this repo is, that the malware/bots aren’t zipped properly. When handling the repo I have already had a few samples escape. It would also be nice if the .rar files had zip file with them. Otherwise though this is a great repo and can’t wait to see what else is in store for it.

**Comment by R00tS3c** [comment]
I will add in future to all. Thanks for suggestion.
