### ISSUE TITLE
Hi RootBash RootShell. I am Genti. Albanius. Can we do together a project. That to have the money of the others in our portofolio. From their Input Phone Numbers, using Twilio for transfering money to our credit card. By giving to others an dashboard with sign up. For open source intelligence tool. As osintdetective.com. The osintdetective accept payment from paypal. Let us do with Twilio. 0.1 percent $ per request. The requests. Are. Username. Phone Number. Email Adress. From Username. To age. Gender . Last name. First name. Location. Birth. Phone numbers. Email addressess. To social links infos. From social links. 

### ISSUE THREAD

**Issue by darknodi** [R00tS3c/DDOS-RootSec#4]
Hi RootBash RootShell. I am Genti. Albanius. Can we do together a project. That to have the money of the others in our portofolio. From their Input Phone Numbers, using Twilio for transfering money to our credit card. By giving to others an dashboard with sign up. For open source intelligence tool. As osintdetective.com. The osintdetective accept payment from paypal. Let us do with Twilio. 0.1 percent $ per request. The requests. Are. Username. Phone Number. Email Adress. From Username. To age. Gender . Last name. First name. Location. Birth. Phone numbers. Email addressess. To social links infos. From social links.

**Comment by darknodi** [comment]
The API are pipl.com
opencnap
everyoneapi. et etc. 


contact me in hangouts arthurbregu@gmail.com

**Comment by darknodi** [comment]
the dashboard we take from creative-tim.com fuly in bootstrap4

**Comment by darknodi** [comment]
@fossabot

**Comment by darknodi** [comment]
@R00tS3c

**Comment by R00tS3c** [comment]
If u need developer contact me at cik3r@protonmail.com
