### ISSUE TITLE
Contact Information?

### ISSUE THREAD

**Issue by RealAchive1** [R00tS3c/DDOS-RootSec#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I'm sorry if I might be waisting your time but I just wanted to know if you can give me some type of contact information so we can talk I've been looking for a dev for a while and need someone with experience in this field.

~ Best regards
RealAchive1

**Comment by R00tS3c** [comment]
teamspeak3 ip: hulk.rs or mail: microfix1252002@gmail.com
