### ISSUE TITLE
I want help

### ISSUE THREAD

**Issue by Cx17-17** [R00tS3c/DDOS-RootSec#96]
I am using kali linux and i dont know how to setup it and how to use it also i just wanna to ddos

**Comment by BustedSec** [comment]
Hi Cx17-17. This is probably not the repository you are looking for. Assuming you are authorized to perform testing for a company and have a signed statement of work, you may want to look at the "Stress Testing" tools in Kali or the items below:

[SlowHTTPTest](https://github.com/shekyan/slowhttptest)
[LOIC](https://github.com/NewEraCracker/LOIC)
[T50](https://github.com/fredericopissarra/t50)
[HULK](https://github.com/grafov/hulk)
[Xerxes](https://github.com/zanyarjamal/xerxes)

**Comment by BustedSec** [comment]
Just a word of advice, if you are not authorized to do this kind of activity, you can get in a lot of trouble for doing so. For example, Operation Payback: In 2010, a group of individuals associated with the hacker collective Anonymous launched a series of DDoS attacks against various organizations. The attacks, which were part of a campaign known as Operation Payback, targeted organizations that had taken actions against file-sharing sites. Several individuals involved in the attacks were later arrested and faced various charges, including conspiracy to commit unauthorized access to a computer system, which carries a maximum penalty of 10 years in prison and a $250,000 fine.

**Comment by Cx17-17** [comment]
Actually no i dont want use the stresser its so useless i know what i am
doing but i dont know how to use this kind of tools and how it works and
what i can do with it so can you just help me?
